version: 1
disable_existing_loggers: true
# Configuring the default (root) logger is highly recommended
root:
  # level: !!python/name:logging.NOTSET
  level: NOTSET
  handlers: [console]
  propagate: yes
loggers:
  ""
handlers:
  logfile:
    class: logging.FileHandler
    filename: sample.log
    formatter: simpleFormatter
    level: !!python/name:logging.NOTSET
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simpleFormatter
    # level: !!python/name:logging.NOTSET
    level: DEBUG
formatters:
  simpleFormatter:
    class: logging.Formatter
    format: '%(name)s %(asctime)s %(levelname)s %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'
